<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="linroad" nsURI="linroad.meta" nsPrefix="hazi.linroad">
  <eClassifiers xsi:type="ecore:EClass" name="XWay">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newEReference" upperBound="100"
        eType="#//Segment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eOperations name="UjAuto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newEReference" upperBound="-1"
        eType="#//Car" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Direction" eType="#//HeadingDir"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Line" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Speed" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HeadingDir">
    <eLiterals name="EAST" literal=""/>
    <eLiterals name="WEST" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Line">
    <eLiterals name="UpRamp"/>
    <eLiterals name="Line1" value="1"/>
    <eLiterals name="Line2" value="2"/>
    <eLiterals name="Line3" value="3"/>
    <eLiterals name="DownRamp" value="4"/>
  </eClassifiers>
</ecore:EPackage>
